import { createHash } from "node:crypto";
import { realpathSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

/**
 * The single owner of on-disk layout. Nothing else builds these strings.
 *
 * State lives under ~/.command-center (override with COMMAND_CENTER_HOME),
 * keyed by the project directory.
 */

export function stateRoot(): string {
  return process.env.COMMAND_CENTER_HOME || join(homedir(), ".command-center");
}

/**
 * Turns a project directory into a filename-safe key.
 *
 * v1 encoded this as `cwd.replace(/\//g, "-")`, which made "/a/b" and "/a-b"
 * both become "a-b" — two unrelated projects silently sharing one state file.
 * The readable slug is kept for humans scanning the directory, but identity
 * comes from a hash of the full path, so distinct projects can never collide.
 */
export function encodeCwd(cwd: string): string {
  const normalized = canonical(cwd).replace(/\/+$/, "") || "/";
  const digest = createHash("sha256").update(normalized).digest("hex").slice(0, 10);
  const slug = normalized
    .split("/")
    .filter(Boolean)
    .slice(-2)
    .join("-")
    .replace(/[^A-Za-z0-9._-]/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 40);

  return slug ? `${slug}-${digest}` : digest;
}

/**
 * Resolves symlinks so one project has one identity.
 *
 * The CLI gets its cwd from `process.cwd()`, which the OS has already resolved
 * to a physical path. A Claude Code hook is handed whatever logical path the
 * session was opened with. On macOS `/var` and `/tmp` are themselves symlinks,
 * so those two can disagree — and then `cmc enable` writes a preference the
 * hook never finds, and the board reports the project as untouched moments
 * after it was set up.
 *
 * A path that does not exist yet is left as-is: it cannot be resolved, and
 * failing here would be worse than a slightly different key.
 */
function canonical(cwd: string): string {
  try {
    return realpathSync.native(cwd);
  } catch {
    return cwd;
  }
}

const dir = {
  state: () => join(stateRoot(), "state"),
  runtime: () => join(stateRoot(), "runtime"),
  locks: () => join(stateRoot(), "locks"),
  logs: () => join(stateRoot(), "logs"),
  prefs: () => join(stateRoot(), "preferences"),
  attachments: () => join(stateRoot(), "attachments"),
};

export const paths = {
  root: stateRoot,
  dirs: () => Object.values(dir).map((f) => f()),

  state: (cwd: string) => join(dir.state(), `${encodeCwd(cwd)}.json`),
  runtime: (cwd: string) => join(dir.runtime(), `${encodeCwd(cwd)}.json`),
  lock: (cwd: string) => join(dir.locks(), `${encodeCwd(cwd)}.lock`),
  log: (cwd: string) => join(dir.logs(), `${encodeCwd(cwd)}.log`),
  prefs: (cwd: string) => join(dir.prefs(), `${encodeCwd(cwd)}.json`),

  /**
   * Attachment bytes, keyed by project and task.
   *
   * Ids are generated by the surface and never come from the uploaded filename,
   * so a file called "../../etc/passwd" cannot escape this directory.
   */
  attachment: (cwd: string, taskId: string, attachmentId: string) =>
    join(dir.attachments(), encodeCwd(cwd), safeSegment(taskId), safeSegment(attachmentId)),
  taskAttachments: (cwd: string, taskId: string) =>
    join(dir.attachments(), encodeCwd(cwd), safeSegment(taskId)),
};

/** Anything that is not a plain id is not allowed to become a path segment. */
function safeSegment(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9._-]/g, "");
  if (cleaned === "" || cleaned === "." || cleaned === "..") {
    throw new Error(`Refusing to build a path from "${value}".`);
  }
  return cleaned;
}
